{% set name = "bluesky-widgets" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bluesky-widgets-{{ version }}.tar.gz
  sha256: 75bf6a04b965de214332b3c6ae77332d96142a8a780d5622372b10f19e1885b3

build:
  number: 1
  noarch: python
  entry_points:
    - queue-monitor = bluesky_widgets.apps.queue_monitor.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bluesky-live >=0.0.7
    - numpy
    - python >=3.6
    - suitcase-utils <=0.5.3

test:
  imports:
    - bluesky_widgets
    - bluesky_widgets.examples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/bluesky-widgets
  summary: Toolbox of widgets for visualizing streaming data
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/bluesky-widgets
  dev_url: https://github.com/bluesky/bluesky-widgets

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
    - AbbyGi
    - danielballan
